#!/bin/bash

# Installation of ICEscreen conda environement from YAML
conda env remove -n icescreen_env
conda env create -f "$(dirname $(readlink -f $0))"/envs/icescreen_env.yml
# Uncomment to install locally
# conda env create --prefix [PATH TO DIR ENVIRONMENT] -f icescreen_env.yml

# If the installation from YAML don't work
# conda create --name icescreen_env --file "$(dirname $(readlink -f $0))"/envs/spec-file.txt

# Last resort... here is how to install from scratch
## Create a Python 3.7 environment
# conda create -n icescreen_env python=3.7 -y
## Install Snakemake v6.0.5 (at least)
# conda install -n icescreen_env -c conda-forge -c bioconda snakemake=6.0.5 -y
## Install Numpy 1.17.4 (at least)
# conda install -n icescreen_env -c conda-forge -c bioconda numpy=1.17.4 -y
## Install Pandas 0.25.3
# conda install -n icescreen_env -c conda-forge -c bioconda pandas=0.25.3 -y
## Install Snakemake v6.0.5 (at least)
# conda install -n icescreen_env -c conda-forge -c bioconda snakemake=6.0.5 -y
## Install Biopython v1.78 (at least) python library
# conda install -n icescreen_env -c conda-forge -c bioconda biopython=1.78 -y
## Install HMMER v3.3.2 (at least)
# conda install -n icescreen_env -c conda-forge -c bioconda hmmer=3.3.2 -y
## Install NCBI BLAST+ suite v2.9.0 (at least)
# conda install -n icescreen_env -c conda-forge -c bioconda blast=2.9.0 -y
## Install BCBio-GFF
# conda install -n icescreen_env -c conda-forge -c bioconda bcbio-gff=0.6.6 -y
## Install YAML
# conda install -n icescreen_env -c conda-forge -c bioconda yaml=0.2.5 -y
