[PARAMS]
maxNumberCDSForSplitSPsByColocalizion = 100
maxNumberCDSForFilterIMESize = 10
groupListSPintoICEsIMEsUsingFamilyInfo = LOOSE
useFamilyInfoToTryToResolveSPModuleConjConflict = YES
useDistanceCDSInfoToTryToResolveSPModuleConjConflict = NO
moveSingleSPToCheck = YES
outputPrintCDSNumberInsteadOfProteinIdAndStart = NO
allowAdjacentIntegraseOnlyForSer = NO
useCDSDistanceToChooseBetweenUpstreamAndDownstreamIntegrase_lowCutoffCDSDistance = 20
useCDSDistanceToChooseBetweenUpstreamAndDownstreamIntegrase_highCutoffCDSDistance = 40

