[PARAMS]
maxNumberCDSForSplitSPsByColocalizion = 100
maxNumberCDSForFilterIMESize = 14
groupListSPintoICEsIMEsUsingFamilyInfo = LOOSE
useFamilyInfoToTryToResolveSPModuleConjConflict = YES
useDistanceCDSInfoToTryToResolveSPModuleConjConflict = NO
moveSingleSPToCheck = YES
# outputPrintCDSNumberInsteadOfProteinIdAndStart = NO
allowAdjacentIntegraseOnlyForSer = NO
useCDSDistanceToChooseBetweenUpstreamAndDownstreamIntegrase_lowCutoffCDSDistance = 20
useCDSDistanceToChooseBetweenUpstreamAndDownstreamIntegrase_highCutoffCDSDistance = 40
maxOverlappingAliLenghtFragmentedSPs = 40
maxCDSDistanceToMergeFragmentedSPs = 150
threshold_blast_ali_identity_perc_transfert_ICEFamily_to_structure_module_conj = 60

